#!/usr/bin/env bash
set -euxo

export XDG_CONFIG_HOME="$HOME/.config"
export DOTFILES_ROOT="$HOME/.dotfiles"

git clone -b "${GITHUB_REF_NAME:-"master"}" https://github.com/ho-oto/dotfiles-for-mac "$DOTFILES_ROOT"
cd "$DOTFILES_ROOT/script"

./brew
[ -d /opt/homebrew ] && eval "$(/opt/homebrew/bin/brew shellenv)" || eval "$(brew shellenv)"

./fisher
./misc
[ -z "${CI:-}" ] && ./mas

./dot
