export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

export DOTFILES_ROOT="$HOME/.dotfiles"
export PATH="$DOTFILES_ROOT/bin:$PATH"
eval "$(/opt/homebrew/bin/brew shellenv)"
export HOMEBREW_NO_UPGRADE_AUTO_UPDATES_CASKS=1

export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

export MANPAGER="sh -c 'col -bx | bat -l man -p'"
