#!/usr/bin/env bash
set -euxo

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# On ARM macOS, brew will be installed to /opt/homebrew
[ -d /opt/homebrew ] && export PATH="/opt/homebrew/bin:$PATH"
[ "$(uname -m)" = "arm64" ] && sudo softwareupdate --install-rosetta

brew update
brew tap homebrew/cask-fonts

formulas=(
    bat
    bottom
    clipper
    cmake
    difftastic
    direnv
    dust
    emacs
    exa
    fd
    fish
    fisher
    fzf
    # gh
    # git
    git-delta
    git-lfs
    htop
    hugo
    hyperfine
    jc
    jq
    latexit
    lazygit
    macos-trash
    mactex-no-gui
    mas
    monolith
    ncdu
    poppler
    procs
    pueue
    ripgrep
    ripgrep-all
    shellcheck
    starship
    tealdeer
    tmux
    tokei
    unar
    viu
    xh
    zoxide
)

formulascask=(
    1password
    1password/tap/1password-cli
    adobe-acrobat-reader
    alfred
    bartender
    bettertouchtool
    deepl
    discord
    dropbox
    firefox
    font-cica
    font-juliamono
    google-chrome
    iterm2
    julia
    krisp
    latexit
    loopback
    mactex-no-gui
    microsoft-edge
    microsoft-office
    monitorcontrol
    pdf-expert
    slack
    spotify
    veracrypt
    visual-studio-code
    wezterm
    xquartz
    zoom
)

for formula in "${formulas[@]}"; do
    if ! brew list --versions "$formula"; then
        brew install "$formula"
    fi
done

for formula in "${formulascask[@]}"; do
    if ! brew list --cask --versions "$formula"; then
        brew install --cask "$formula"
    fi
done

brew services start clipper
brew services start pueue
