#!/usr/bin/env bash
set -euxo

[ -z "${XDG_CONFIG_HOME:-}" ] && XDG_CONFIG_HOME="$HOME/.config"

dirshome=(
    julia/config
    config
    hammerspoon
)
fileshome=(
    zshrc
    zprofile
    emacs.el
    tmux.conf
    julia/config/startup.jl
    config/starship.toml # location of starship.toml is $HOME/.config, not $XDG_CONFIG_HOME
    hammerspoon/init.lua
)

dirsxdgc=(
    fish
    git
    wezterm
    broot
)
filesxdgc=(
    fish/config.fish
    git/config
    git/ignore
    wezterm/wezterm.lua
    broot/conf.toml
)

mkdir -p "$XDG_CONFIG_HOME"

for DIR in "${dirshome[@]}"; do
    mkdir -p "$HOME/.$DIR"
done
for FILE in "${fileshome[@]}"; do
    rm -f "$HOME/.$FILE"
    ln -s "$DOTFILES_ROOT/config/$FILE" "$HOME/.$FILE"
done

for DIR in "${dirsxdgc[@]}"; do
    mkdir -p "$XDG_CONFIG_HOME/$DIR"
done
for FILE in "${filesxdgc[@]}"; do
    rm -f "$XDG_CONFIG_HOME/$FILE"
    ln -s "$DOTFILES_ROOT/config/xdg/$FILE" "$XDG_CONFIG_HOME/$FILE"
done
