#!/usr/bin/env bash
set -euxo pipefail

# Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y --no-modify-path

# Rye (Python)
curl -LsSf https://astral.sh/uv/install.sh | UV_NO_MODIFY_PATH=1 sh

# mise
curl https://mise.run | bash
