#!/usr/bin/env bash
set -euxo

export DOTFILES_ROOT="$HOME/.dotfiles"
git clone https://github.com/ho-oto/dotfiles-for-mac "$DOTFILES_ROOT"
cd "$DOTFILES_ROOT/script"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.share"

./dot
./brew
./pyenv
./fisher
./tmux
./cargo
if [ -z "${CI:-}" ]; then ./mas; fi

cat <<EOF
You have to do the following:
1. run tmux and press prefix + I to fetch plugins
EOF
