#!/bin/bash
set -euxo

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

if [ -d /opt/homebrew ]; then # On ARM macOS, brew will be installed to /opt/homebrew
    export PATH="/opt/homebrew/bin:$PATH"
fi

formulas=(
    bat
    clipper
    cmake
    dust
    emacs
    exa
    fd
    fish
    fzf
    gh
    git
    git-delta
    htop
    hugo
    hyperfine
    latexit
    lazygit
    macos-trash
    mactex-no-gui
    mas
    monolith
    ncdu
    poppler
    procs
    ripgrep
#    ripgrep-all # will be builded by cargo
#    shellcheck
    starship
    tealdeer
    tmux
    tokei
    unar
    zoxide
)

formulascask=(
    1password
    authy
    bartender
    bettertouchtool
    discord
    dropbox
    firefox
    font-cica
    font-juliamono
    google-chrome
    iterm2
    julia
    krisp
    microsoft-office
    pdf-expert
    slack
    spotify
    visual-studio-code
    wolfram-engine
    xquartz
    zoom
)


brew update

for formula in "${formulas[@]}"; do
    if ! brew list --versions "$formula"; then
        brew install "$formula"
    fi
done

brew tap homebrew/cask-fonts
if [[ "$(uname -m)" == "arm64" ]]; then
    sudo softwareupdate --install-rosetta
fi

for formula in "${formulascask[@]}"; do
    if ! brew list --cask --versions "$formula"; then
        brew install --cask "$formula"
    fi
done

brew services start clipper
