#!/bin/bash
set -euxo pipefail

git clone https://github.com/pyenv/pyenv.git "$HOME/.pyenv"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

PYTHON_VERSION=$(pyenv install -l | grep '^ *3.[0-9].[0-9]' | sort --version-sort | tail -n 1 | sed 's/ *//')
pyenv install "$PYTHON_VERSION"

cd "$(mktemp -d)" || { echo "Failed to move to tempdir"; exit 1; }
pyenv local "$PYTHON_VERSION"
pip install --upgrade pip
pip install numpy scipy ipython jupyter jupyterlab
